maxplanck-ie/nanoporeReads_dataTransfer

misc/sendEmail.py

added misc

---

AUTHORS
ChangeLog
config.template.yaml
env.yaml
setup.cfg
src/npr/ont.py
src/npr/rules/1_basecalling.smk
src/npr/rules/2_rename.smk
src/npr/rules/3_qc.smk
src/npr/rules/4_data_transfer.smk
src/npr/rules/ont_pipeline.smk
src/npr/snakehelper.py

Adds Fastqc to suite of QC tools. 
Additional refactoring:
* aggregate pipeline config YAML into metadata pandas DataFrame
* add more cores for Snakemake
* refactoring of 2_rename and 3_qc to include input/output files

Add fastqc support

---

src/npr/rules/4_data_transfer.smk

yaml init with flowcell / kit / model for end users.

yaml end users

---

src/npr/communication.py

more escapes.

---

src/npr/communication.py
src/npr/ont.py

imports & syntax

---

README.md

updated installation instructions

---

src/npr/rules/3_qc.smk

somehow this was omitted from the last PR

3_qc.smk: swallow kraken output

---

src/npr/communication.py
src/npr/snakehelper.py

- parkour_query fix: previously tried to access config["data"]["Sample_Project"] which is unavailable
- pod5_merge fix: recursive merge did not work properly

fix bug in parkour_query and recursive merging of pod5

---

misc/tidyNanopore.py
src/npr/ont_pipeline.py

- Adding cleaning backups script
- Checking if SampleSheet.csv is on Flowcell directory (in preparation for an automatic retrieval from Parkour)

Updates pr149

---

src/npr/rules_dorado/00_prepare.smk

adding "flowcell/pod5" directory in addition of "flowcell/pod5_pass" and "flowcell/pod5_fail"

adding flowcell/pod5 as another pod dir

---

src/npr/rules_dorado/01_basecall.smk
src/npr/rules_dorado/06_align.smk
src/npr/rules_dorado/07_modbed.smk

bash variable comparison was failing over shell commands

fixing error in variable comparison for Bash command

---

src/npr/rules_dorado/01_basecall.smk
src/npr/rules_dorado/06_align.smk
src/npr/rules_dorado/07_modbed.smk

fixing variable evaluation on bash commands

fix for bash variable context

---

src/npr/rules_dorado/06_align.smk

Creating the transfer/proj/Analysis directory if needed

creating the transfer/proj/Analysis dir if needed

---

config.template.yaml
src/npr/ont_pipeline.py
src/npr/rules_dorado/01_basecall.smk
src/npr/rules_dorado/06_align.smk
src/npr/rules_dorado/07_modbed.smk

Avoiding using "yes", "no" and "true", "false" for flags as python and bash evaluation problems

avoiding yes/no and true/false for flags as python/bash eval problems

---

.pre-commit-config.yaml
config.template.yaml
src/npr/ont_pipeline.py
src/npr/rules_dorado/01_basecall.smk
src/npr/rules_dorado/06_align.smk
src/npr/rules_dorado/07_modbed.smk
src/npr/rules_dorado/09_transfer.smk

Main changes:
- flags checks between yaml/python/bash
- bug for existing target dir

Minor integration for v2.0.6

---

config.template.yaml
src/npr/communication.py
src/npr/ont_pipeline.py
src/npr/rules_dorado/00_prepare.smk
src/npr/rules_dorado/ont_pipeline.smk

Added communication for when no reference genome is found and SampleSheet from parkour

Added communication for when no reference genome is found and SampleSheet from parkour

---

ChangeLog
src/npr/communication.py
src/npr/rules_dorado/ont_pipeline.smk

Added GRCm39 and GRCh37

---

config.template.yaml
src/npr/communication.py

Deprecated 'get_organism_name' function 

---

ChangeLog
src/npr/rules_dorado/00_prepare_bam.smk
src/npr/rules_dorado/ont_pipeline.smk

- adds functionality to deal with demultiplexed input data from source path

Implement sample and batch wildcards

---

src/npr/ont.py
src/npr/snakehelper.py

feat: include elapsed time in config
